### ISSUE TITLE
Support css urls

### ISSUE THREAD

**Issue by jdf-id-au** [getpelican/pelican#2286]
I'm rolling a theme which uses css background images.
```css
section.classname {
  background-image: url('path/to/image.jpg');
}
```

It would be good if these urls could be re-written taking account of `{{ SITEURL }}`.
