### ISSUE TITLE
Missing theme folder in output (Gitlab)

### ISSUE THREAD

**Issue by statiksof** [getpelican/pelican#2800]
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

In the log file of the gitlab CI I see:

`WARNING: Empty theme folder. Using `basic` theme.`

In `output` there is no `theme` folder. I use `pelican content -s pelicanconf.py` to generate the html files.

Locally, it works. Only in Gitlab.

**Comment by avaris** [comment]
Without seeing your GitLab and CI setup, I can only guess about the issue. So, here is a shot in the dark: You added the theme as a submodule but [in your CI you don't pull it](https://docs.gitlab.com/ee/ci/git_submodules.html#using-git-submodules-in-your-ci-jobs).

**Comment by statiksof** [comment]
@avaris thank you for your quick reply. The repo is currently private but here my CI setup:

```
pages:
  before_script:
      - apk update && apk upgrade && apk add py3-pip git make
      - pip3 install --upgrade pip
      - pip install -r requirements.txt
  
  script:
      - make publish

  only:
      - master

  artifacts:
    paths:
    - public
    expire_in: 5min

```

I modified as you suggested the CI by adding this: 

```
variables:
  GIT_SUBMODULE_STRATEGY: recursive
```

and it works now.
