### ISSUE TITLE
YAML based authors paged

### ISSUE THREAD

**Issue by ebanDev** [getpelican/pelican#2924]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

Hello ! I have a blog with multiple authors, and on the authors page I need to display some informations about authors (like their social networks, profile picture etc.). I wonder if I could do that with pelican, maybe in YAML ? Could be something like that :
```yaml
AnAuthor:
    ProfilePicture: https://example.com/pic.jpg
    Twitter: https://twitter.com/AnAuthor
AnOtherAuthor:
    ProfilePicture: https://example.org/picture.jpg
    Twitter: https://twitter.com/AnOtherAuthor
    Github: https://twitter.com/AnOtherAuthorDev
```

And rendered in HTML like this (not the same author name but just to show an example ;)) :
![image](https://user-images.githubusercontent.com/57091497/135304254-9f4bf392-7d49-4f83-bdde-fb166d631848.png)

Thanks :)
