### ISSUE TITLE
More pre-commit filters, e.g. isort

### ISSUE THREAD

**Issue by boxydog** [getpelican/pelican#3216]
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [X] I am willing to lend a hand to help implement this feature. 

## Feature Request

I submitted a pull request that passed pre-commit but failed lint checks, because of import order.

[isort](https://pycqa.github.io/isort/docs/configuration/pre-commit.html) is a pre-commit filter that I think would've fixed my import order. I feel like we should add it.

Some others I'd recommend, in rough order:

- pyupgrade
- autoflake
- black
- pylint

- pre-commit check-case-conflict, check-docstring-first, check-merge-conflict, check-symlinks, debug-statement, mixed-line-ending, forbid-crlf, forbid-tabs

I understand that adding each of these would result in code shift getting the project to pass. My approach would be to add them all, see which are easy to keep, and drop the rest for now. Time box to a couple hours.

It has this problem that it would conflict with every other PR, so I would want permission to get it in fairly quickly, otherwise resolving conflicts becomes too painful.

Below is a sample pre-commit from one of my projects. It's not a perfect fit, but I could adjust it. For example, versions. I was targeting newer pythons, but could tune it back to python 3.7, which seems to be the oldest one you test.

```
# See http://pre-commit.com/#python
# See https://github.com/pre-commit/pre-commit-hooks
# Run 'pre-commit install' to install the pre-commit hooks
repos:

# See also https://adamj.eu/tech/2021/09/16/introducing-django-upgrade/
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [ --py39-plus ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: detect-private-key
  # black handles quoting
  # - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: (.csv|.tsv)$
  - id: pretty-format-json
    args: ['--no-sort-keys', '--autofix']
  # don't commit directly to main or master
  - id: no-commit-to-branch

- repo: https://github.com/myint/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
    args:
      - --in-place
      - --remove-unused-variables
      - --remove-all-unused-imports

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    language_version: python3.11
    exclude: migrations/

# flake8 after black, so black can fix formatting first
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    exclude: migrations/

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
        - --src=dir1,dir2
        # See also https://jugmac00.github.io/blog/isort-and-pre-commit-a-friendship-with-obstacles/
        - --filter-files
        - --skip-glob=*/migrations/*.py
        # line length must match black and flake8
        - --profile=black

- repo: https://github.com/PyCQA/pylint
  rev: v3.0.1
  hooks:
    - id: pylint
      args:
        # black is controlling line length:
        - --disable=line-too-long
        # let's not worry too much right now about dup code.
        - --disable=duplicate-code
        - --disable=fixme
        - --disable=import-error
        - --disable=logging-fstring-interpolation
        - --disable=missing-class-docstring
        - --disable=missing-function-docstring
        - --disable=missing-module-docstring
        - --disable=too-few-public-methods
        - --disable=too-many-arguments
        # - --disable=too-many-branches
        - --disable=too-many-locals
        # isort is taking care of import order:
        - --disable=wrong-import-order
        # re-enable these args
        - --disable=unused-argument
        - --disable=invalid-name
        - --disable=raise-missing-from

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
  - id: forbid-crlf
    exclude: ^dir1/.*.csv
  # don't just remove, seems dangerous
  # - id: remove-crlf
  - id: forbid-tabs
    # tests.py has a test with a tab in it
    # jquery is auto-generated code
    exclude: (.tsv|dir2/tests/tests.py)$
  # don't just remove, seems dangerous
  # - id: remove-tabs
```
