### ISSUE TITLE
How to use the github action with a theme?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [getpelican/pelican#3308]
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
I'm trying to use the [provided github action](https://docs.getpelican.com/en/4.9.1/tips.html#publishing-to-github-pages-using-a-custom-github-actions-workflow) to deploy my site.  Locally, I've run `pelican-themes --install path/to/pelican-themes/Flex`, having cloned that repo.  The action sees my `THEME` in pelicanconfig.py and raises the error "CRITICAL Exception: Could not find the theme"

My jobs:
```
jobs:
  theme:
    name: install theme
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "alexandrevicenzi/Flex"
        ref: "v2.5.0"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: actions/checkout@v4
    - name: "install dependencies"
      run: |
        pip install -r requirements.txt
        pelican-themes --install ./Flex
  deploy:
    needs: theme
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@master"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"
      requirements: "-r requirements.txt"
```

My actions look like:
![image](https://github.com/getpelican/pelican/assets/37048747/0f5eae99-c894-404a-a22d-57e7f36cd7e4)
